HEADERS = ["_id",
    "CH_SYMBOL",
    "CH_SERIES",
    "CH_MARKET_TYPE",
    "CH_TRADE_HIGH_PRICE",
    "CH_TRADE_LOW_PRICE",
    "CH_OPENING_PRICE",
    "CH_CLOSING_PRICE",
    "CH_LAST_TRADED_PRICE",
    "CH_PREVIOUS_CLS_PRICE",
    "CH_TOT_TRADED_QTY",
    "CH_TOT_TRADED_VAL",
    "CH_52WEEK_HIGH_PRICE",
    "CH_52WEEK_LOW_PRICE",
    "CH_TOTAL_TRADES",
    "CH_ISIN",
    "CH_TIMESTAMP",
    "TIMESTAMP",
    "createdAt",
    "updatedAt",
    "__v",
    "COP_DELIV_QTY",
    "COP_DELIV_PERC",
    "VWAP",
    "mTIMESTAMP"]

NIFTY_FIFTY_STOCKS = "nifty_50stocks";
NIFTY_NEXT_50_LIST_STOCKS="nifty_next50list";
NIFTY_100_LIST_STOCKS="nifty_100list";
NIFTY_200_LIST_STOCKS="nifty_200list";
NIFTY_500_LIST_STOCKS="nifty_500list";
NIFTY_MICRO_CAP_250_LIST_STOCKS="nifty_microcap250_list";
NIFTY_MID_CAP_50_LIST_STOCKS="nifty_midcap50list";
NIFTY_MID_CAP_100_LIST_STOCKS="nifty_midcap100list";
NIFTY_MID_CAP_150_LIST_STOCKS="nifty_midcap150list";
NIFTY_MID_CAP_SELECT_LIST_STOCKS="nifty_midcapselect_list";
NIFTY_MID_SMALL_CAP_400_LIST_STOCKS="nifty_midsmallcap400list";
NIFTY_SMALL_CAP_50_LIST_STOCKS="nifty_smallcap50list";
NIFTY_SMALL_CAP_100_LIST_STOCKS="nifty_smallcap100list";
NIFTY_SMALL_CAP_250_LIST_STOCKS="nifty_smallcap250list";
NIFTY_BANK_STOCKS="nifty_bankstocks";

NIFTY_FIFTY="NIFTY_FIFTY";
NIFTY_NEXT_50_LIST="NIFTY_NEXT_50_LIST";
NIFTY_100_LIST="NIFTY_100_LIST";
NIFTY_200_LIST="NIFTY_200_LIST";
NIFTY_500_LIST="NIFTY_500_LIST";
NIFTY_MICRO_CAP_250_LIST="NIFTY_MICRO_CAP_250_LIST";
NIFTY_MID_CAP_50_LIST="NIFTY_MID_CAP_50_LIST";
NIFTY_MID_CAP_100_LIST="NIFTY_MID_CAP_100_LIST";
NIFTY_MID_CAP_150_LIST="NIFTY_MID_CAP_150_LIST";
NIFTY_MID_CAP_SELECT_LIST="NIFTY_MID_CAP_SELECT_LIST";
NIFTY_MID_SMALL_CAP_400_LIST="NIFTY_MID_SMALL_CAP_400_LIST";
NIFTY_SMALL_CAP_50_LIST="NIFTY_SMALL_CAP_50_LIST";
NIFTY_SMALL_CAP_100_LIST="NIFTY_SMALL_CAP_100_LIST";
NIFTY_SMALL_CAP_250_LIST="NIFTY_SMALL_CAP_250_LIST";
NIFTY_BANK="NIFTY_BANK";


NIFTY_BANK_LIST = ["SBIN","AXISBANK","INDUSINDBK","PNB","BANDHANBNK","ICICIBANK","FEDERALBNK","IDFCFIRSTB","HDFCBANK","KOTAKBANK","BANKBARODA","ICICIBANK"]
