HEADERS = [
    "_id",
    "CH_SYMBOL",
    "CH_SERIES",
    "CH_MARKET_TYPE",
    "CH_TRADE_HIGH_PRICE",
    "CH_TRADE_LOW_PRICE",
    "CH_OPENING_PRICE",
    "CH_CLOSING_PRICE",
    "CH_LAST_TRADED_PRICE",
    "CH_PREVIOUS_CLS_PRICE",
    "CH_TOT_TRADED_QTY",
    "CH_TOT_TRADED_VAL",
    "CH_52WEEK_HIGH_PRICE",
    "CH_52WEEK_LOW_PRICE",
    "COP_DELIV_QTY",
    "COP_DELIV_PERC",
    "CH_TOTAL_TRADES",
    "VWAP",
    "CH_TIMESTAMP",
    "CH_ISIN",
    "createdAt",
    "updatedAt",
    "TIMESTAMP",
    "mTIMESTAMP"
    ];

FILTERS_HEADERS = [
    "mTIMESTAMP",
    "CH_SYMBOL",
    "COP_DELIV_PERC",
    "COP_DELIV_QTY",
    "CH_TOT_TRADED_QTY",
    "CH_OPENING_PRICE",
    "CH_TRADE_HIGH_PRICE",
    "CH_TRADE_LOW_PRICE",
    "CH_CLOSING_PRICE",
    "CH_52WEEK_HIGH_PRICE",
    "CH_52WEEK_LOW_PRICE",
    "CH_TOTAL_TRADES",
    "CH_LAST_TRADED_PRICE",
    "CH_PREVIOUS_CLS_PRICE",
    "VWAP",
    "CH_TIMESTAMP",
    "CH_ISIN",
    "createdAt",
    "updatedAt",
    "TIMESTAMP",
    "CH_TOT_TRADED_VAL",
    "CH_SERIES"
    ];

DEALS_HEADERS= ['DATE', 'STOCK_SYMBOL', 'STOCK_NAME', 'CLIENT_NAME', 'BUY_OR_SELL', 'TRADED_QUANTITY', 'WATP', 'REMARKS'];
DEALS_CUSTOM_HEADERS = ["ID","DATE","STOCK_SYMBOL","STOCK_NAME","CLIENT_NAME","BUY_OR_SELL","TRADED_QUANTITY","WATP","Created At","Updated At","TIMESTAMP"];
DEALS_KEYS = ['date', 'symbol', 'name', 'clientName', 'buySell', 'qty', 'watp', 'remarks']

NIFTY_FIFTY_STOCKS = "nifty_50stocks";
NIFTY_NEXT_50_LIST_STOCKS="nifty_next50list";
NIFTY_100_LIST_STOCKS="nifty_100list";
NIFTY_200_LIST_STOCKS="nifty_200list";
NIFTY_500_LIST_STOCKS="nifty_500list";
NIFTY_MICRO_CAP_250_LIST_STOCKS="nifty_microcap250_list";
NIFTY_MID_CAP_50_LIST_STOCKS="nifty_midcap50list";
NIFTY_MID_CAP_100_LIST_STOCKS="nifty_midcap100list";
NIFTY_MID_CAP_150_LIST_STOCKS="nifty_midcap150list";
NIFTY_MID_CAP_SELECT_LIST_STOCKS="nifty_midcapselect_list";
NIFTY_MID_SMALL_CAP_400_LIST_STOCKS="nifty_midsmallcap400list";
NIFTY_SMALL_CAP_50_LIST_STOCKS="nifty_smallcap50list";
NIFTY_SMALL_CAP_100_LIST_STOCKS="nifty_smallcap100list";
NIFTY_SMALL_CAP_250_LIST_STOCKS="nifty_smallcap250list";
NIFTY_BANK_STOCKS="nifty_bankstocks";

NIFTY_FIFTY="NIFTY_FIFTY";
NIFTY_NEXT_50_LIST="NIFTY_NEXT_50_LIST";
NIFTY_100_LIST="NIFTY_100_LIST";
NIFTY_200_LIST="NIFTY_200_LIST";
NIFTY_500_LIST="NIFTY_500_LIST";
NIFTY_MICRO_CAP_250_LIST="NIFTY_MICRO_CAP_250_LIST";
NIFTY_MID_CAP_50_LIST="NIFTY_MID_CAP_50_LIST";
NIFTY_MID_CAP_100_LIST="NIFTY_MID_CAP_100_LIST";
NIFTY_MID_CAP_150_LIST="NIFTY_MID_CAP_150_LIST";
NIFTY_MID_CAP_SELECT_LIST="NIFTY_MID_CAP_SELECT_LIST";
NIFTY_MID_SMALL_CAP_400_LIST="NIFTY_MID_SMALL_CAP_400_LIST";
NIFTY_SMALL_CAP_50_LIST="NIFTY_SMALL_CAP_50_LIST";
NIFTY_SMALL_CAP_100_LIST="NIFTY_SMALL_CAP_100_LIST";
NIFTY_SMALL_CAP_250_LIST="NIFTY_SMALL_CAP_250_LIST";
NIFTY_BANK="NIFTY_BANK";


NIFTY_BANK_LIST = ["SBIN","AXISBANK","INDUSINDBK","PNB","BANDHANBNK","ICICIBANK","FEDERALBNK","IDFCFIRSTB","HDFCBANK","KOTAKBANK","BANKBARODA","ICICIBANK"];

INPUT_TYPE_INDICES = "INDICES";
INPUT_TYPE_STOCKS = "STOCKS";
INPUT_TYPE_ALL = "ALL";
INPUT_TYPE_LARGE_DEALS = "LARGE_DEALS";
INPUT_TYPE_LARGE_DEALS_CUSTOMIZATION = "LARGE_DEALS_CUSTOMIZATION";
REPORTS_DIR = "H://NSEReports//";
