import os
import nse_security_wise_archive as nseSecurityWiseArchive;
import logging
from utils import getAutoGeneratedLogFileName
import constants

def logConfig(logFileName):
    # DEBUG MODE
    # logging.basicConfig(
    #     filename= os.path.join('logs', logFileName),
    #     format='%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s',
    #     level=logging.DEBUG
    # )

    # NORMAL MODE
    logging.basicConfig(
        filename= os.path.join('logs', logFileName),
        format='%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s',
        level=logging.INFO
    )

def main():
    logFileName = getAutoGeneratedLogFileName(constants.NIFTY_FIFTY_STOCKS);
    logConfig(logFileName)
    nseSecurityWiseArchive.nseGenerateSecurityWiseArchiveReport();

main();