import datetime
import os
from nse_nifty_indices_stocks_list import getNiftyIndicesStocksList
import nse_security_wise_archive as nseSecurityWiseArchive;
import logging
from utils import getAutoGeneratedLogFileName,getAutoGeneratedFileName
from constants import *
import nse_read_user_inputs as nseReadUserInputs
import nse_index_stocks_list as nseIndexStocksList
from filenames import *

def logConfig(logFileName):
    # DEBUG MODE
    # logging.basicConfig(
    #     filename= os.path.join('logs', logFileName),
    #     format='%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s',
    #     level=logging.DEBUG
    # )
    datefolder = datetime.datetime.now().strftime('%d%m%Y');
    folderPath = 'logs//'+datefolder;
    if os.path.exists(folderPath):
        print("folder already exits")
    else:
        path = os.path.join("logs", datefolder);
        os.makedirs(path)
    
    # NORMAL MODE
    logging.basicConfig(
        filename= os.path.join(folderPath, logFileName),
        format='%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s',
        level=logging.INFO
    )

def main():
    fileName = '';
    stockList = [];
    input = nseReadUserInputs.getInputs();
    selectedType:str = input['selectedNseDataType'];
    logConfig(getAutoGeneratedLogFileName(selectedType))
    if(selectedType == NIFTY_FIFTY):
        fileName = getAutoGeneratedFileName(NIFTY_FIFTY_STOCKS);
        stockList = nseIndexStocksList.getNiftyFiftyStockList();
        print(stockList);
    elif (selectedType == NIFTY_NEXT_50_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_NEXT_50_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_NEXT_50_LIST_FILENAME);
    elif (selectedType == NIFTY_100_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_100_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_100_LIST_FILENAME);
    elif (selectedType == NIFTY_500_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_500_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_500_LIST_FILENAME);
    elif (selectedType == NIFTY_MICRO_CAP_250_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_MICRO_CAP_250_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_MICRO_CAP_250_LIST_FILENAME);
    elif (selectedType == NIFTY_MID_CAP_50_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_MID_CAP_50_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_MID_CAP_50_LIST_FILENAME);
    elif (selectedType == NIFTY_MID_CAP_100_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_MID_CAP_100_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_MID_CAP_100_LIST_FILENAME);
    elif (selectedType == NIFTY_MID_CAP_150_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_MID_CAP_150_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_MID_CAP_150_LIST_FILENAME);
    elif (selectedType == NIFTY_MID_CAP_SELECT_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_MID_CAP_SELECT_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_MID_CAP_SELECT_LIST_FILENAME);
    elif (selectedType == NIFTY_MID_SMALL_CAP_400_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_MID_SMALL_CAP_400_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_MID_SMALL_CAP_400_LIST_FILENAME);
    elif (selectedType == NIFTY_SMALL_CAP_50_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_SMALL_CAP_50_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_SMALL_CAP_50_LIST_FILENAME);
    elif (selectedType == NIFTY_SMALL_CAP_100_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_SMALL_CAP_100_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_SMALL_CAP_100_LIST_FILENAME);
    elif (selectedType == NIFTY_SMALL_CAP_250_LIST):
        fileName = getAutoGeneratedFileName(NIFTY_SMALL_CAP_250_LIST_STOCKS);
        stockList = getNiftyIndicesStocksList(NIFTY_SMALL_CAP_250_LIST_FILENAME);
    elif (selectedType == NIFTY_BANK):
        fileName = getAutoGeneratedFileName(NIFTY_BANK_STOCKS);
        stockList = NIFTY_BANK_LIST;
    else:
        fileName = getAutoGeneratedFileName(NIFTY_FIFTY_STOCKS);
        stockList = nseIndexStocksList.getNiftyFiftyStockList();
    nseSecurityWiseArchive.nseGenerateSecurityWiseArchiveReport(fileName,stockList,selectedType);

main();