from nsepython import *
import nse_report_writer as nseReportWriter
import nse_index_stocks_list as nseIndexStocksList
import nse_apis as nseApis
import utils as utils;
import constants as constants
import logging as log

def nseGenerateSecurityWiseArchiveReport():
    toDate = utils.getTodayDate();
    fromDate= utils.getPastWeekDate();
    log.info(f"Report is generating is Started and the period is from {fromDate} to {toDate}");
    niftyFiftyList = nseIndexStocksList.getNiftyFiftyStockList();
    log.info("List of Nifty Fifty Stock Symbols are displaying below Please check");
    log.info(niftyFiftyList);
    listOfDics = [];
    log.info(f"Started Process for getting the list of nse security wise archive data.")
    for stockSymbol in niftyFiftyList :
        log.info(f"{stockSymbol} Stock Started fetching the data from server.....")
        result = nseApis.security_wise_archive(fromDate, toDate,stockSymbol)
        listOfDics.extend(result);
        log.info(f"{stockSymbol} Stock Completed fetching the data from server.....")

    log.info("Completed Process for getting the list of nse security wise archive data.")
    log.info("Number of records fetched from Api is ");
    fileName = utils.getAutoGeneratedFileName(constants.NIFTY_FIFTY_STOCKS);
    log.info(f"Started writing Security wise archive Data to CSV and filename is {fileName}");
    nseReportWriter.writeDataToCSV(fileName,constants.NIFTY_FIFTY_HEADERS,listOfDics)
    log.info(f"Completed writing Security wise archive Data to CSV and filename is {fileName}");
    log.info(f"Report is generating is completed and the period is from {fromDate} to {toDate}");