import datetime

def getPastWeekDate():
    N_DAYS_AGO = 7
    today = datetime.datetime.now()
    n_days_ago = today - datetime.timedelta(days=N_DAYS_AGO)
    strDate = n_days_ago.strftime("%d-%m-%Y");
    return strDate;
    
def getTodayDate():
    today = datetime.datetime.now()
    strDate = today.strftime("%d-%m-%Y");
    return strDate;

def getAutoGeneratedFileName():
    strDate = datetime.datetime.now().strftime("%d%m%Y_%H%M%S");
    fileName = "H://NSEReports//security_wise_archive_"+strDate+".csv";
    return fileName;