import datetime
import os
from constants import REPORTS_DIR

def getPastWeekDate(noOfDaysFromPresent):
    today = datetime.datetime.now()
    n_days_ago = today - datetime.timedelta(days=noOfDaysFromPresent)
    strDate = n_days_ago.strftime("%d-%m-%Y");
    return strDate;
    
def getTodayDate():
    today = datetime.datetime.now()
    strDate = today.strftime("%d-%m-%Y");
    return strDate;

def getAutoGeneratedFileName(strFileType,reportsDir):
    strDate = datetime.datetime.now().strftime("%d%m%Y_%H%M%S");
    datefolder = datetime.datetime.now().strftime("%d%m%Y");
    folderPath = reportsDir+datefolder;
    if os.path.exists(folderPath):
        print("folder already exits")
    else:
         path = os.path.join(reportsDir, datefolder)
         os.makedirs(path);
   
    fileName = reportsDir+datefolder+"//security_wise_archive_"+strFileType+"_data_"+strDate;
    return fileName;


def getAutoGeneratedLogFileName(strFileType):
    strDate = datetime.datetime.now().strftime("%d%m%Y_%H%M%S");
    fileName = "logs_security_wise_archive_"+strFileType+"_data_"+strDate+".log";
    return fileName;